{
    "projects": {
        "prisma": {
            "schemaPath": "src/generated/prisma.graphql",
            "extensions": {
                "prisma": "prisma/prisma.yml",
                "endpoints": {
                    "default": {
                        "url": "http://localhost:4466/",
                        "headers": {
                            "Authorization": "Bearer ${env:API_TOKEN}"
                        }
                    }
                }
            }
        }
    }
}